name: Schedule Test Runs

on:
  schedule:
    # Modify this to specify when the job should run. The below is daily at 12 AM GMT
    - cron: '0 0 * * *'
  # Allows the workflow to be run manually through the GitHub UI
  workflow_dispatch:

jobs:
  schedule_tests:
    strategy:
      matrix:
        sf_org_alias: [INTEGRATION, UAT]

    env:
        ENVIRONMENT: ${{ matrix.sf_org_alias }}

    runs-on: ubuntu-latest

    steps:

    - run: echo what is the secret ${{ secrets[format('SFDX_{0}_URL', env.ENVIRONMENT)] }}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Salesforce CLI
      run: |
        apt-get update
        apt-get install -y curl git python3 
        curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
        apt-get install -y nodejs
        npm install --global @salesforce/cli@latest
        sf version --verbose --json

    - name: Authenticate to Org
      run: python3 ./authenticate_sf.py --alias ${{ matrix.sf_org_alias }} --url ${{ secrets[format('SFDX_{0}_URL', env.ENVIRONMENT)] }}

    - name: Run all tests and store test run Id
      run: |
        sf apex run test --test-level RunLocalTests --result-format human > ./id.txt
        echo "$(node ./extractId.js)" > ${{ matrix.sf_org_alias }}_test_run_id.txt

    - name: Upload the test run Id as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.sf_org_alias }}_test_run_id
        path: ${{ matrix.sf_org_alias }}_test_run_id.txt
